Alberto/atqr 92 refactor controller methods
tokilabs/atqr pull request #31
Opened 2022-09-01 17:00 UTC by albnunes

I made endpoint responsible for a group of methods and the services in front are updated.

2022-09-01 21:18 UTC, albnunes commented
https://linear.app/toki-labs/issue/ATQR-92/refactor-controller-methods

2022-11-14 14:54 UTC, yfernandes commented
Hey @rairezende and @albnunes I'll be reviewing this one.  @albnunes since there are only two conflicting files I can take care of those for you

2022-11-14 15:56 UTC, yfernandes requested changes
Major changes looks fine, but there are missing dependencies i can't find anywhere. Those have to be  resolved before being approved.

2022-11-14 15:56 UTC, yfernandes commented on apps/atqr/api/src/app/dtos/index.ts
> +export * from './updateChallenge.dto'
A update challenge dto is imported but one is never created

2022-11-14 15:56 UTC, yfernandes commented on apps/atqr/api/src/app/app.module.ts
> +import { PatchMiddleware } from './middleware/patchMiddleware';
There is no reference to a patch middleware, are you sure it really exists?

2022-11-14 15:56 UTC, yfernandes commented on apps/atqr/api/src/app/app.module.ts
> +    .forRoutes({ path: 'challenge/:id', method: RequestMethod.PATCH });
Configuration for missing dependency.

2022-11-14 17:44 UTC, yfernandes approved these changes
After changes everything is working!

2022-11-14 18:03 UTC, merged