(Gabi will edit) mapping from prisma entities to domain #67
tokilabs/atqr pull request #36
Opened 2022-10-04 19:27 UTC by svallory

2022-10-26 21:56 UTC, antonio-marcos1989 submitted a review, later dismissed

2022-11-11 20:38 UTC, albnunes commented
Do a rebase

2022-11-29 18:58 UTC, yfernandes commented on apps/atqr/api/src/app/challenge.controller.ts
> +   async updateStatus(id: Guid, status: ChallengeStatus): Promise<void> {
Why were the method and controller decorators decorator deleted?

2022-11-29 19:13 UTC, yfernandes commented
This PR has 37 modified files, spanning 3 projects, most changes have no connection with each other, and the PR has no description.

@albnunes and I are looking for a place to start reviewing for at least 30min. Please provide a clear description of your PR and clean your commit history.

2022-11-29 19:16 UTC, yfernandes requested changes
This PR has 37 modified files, spanning 3 projects, most changes have no connection with each other, and the PR has no description.

@albnunes and I are looking for a place to start reviewing for at least 30min. Please provide a clear description of your PR and clean your commit history. This PR is about mapping Prisma entities to domain, and it should be reserved for that!

2022-12-02 13:16 UTC, closed without merging