feat: added pug style file that has style css
tokilabs/atqr pull request #44
Opened 2022-11-17 20:07 UTC by rairezende

turned the base pug style file into a css file and created a pug file that contains it + some style links. This file is then used by the email pug templates though the include keyword.

2022-11-17 21:31 UTC, yfernandes commented on libs/atqr/domain/src/lib/EmailService/templates/includes/base-style.scss
> +  $color_1: #272727;
As a rule of thumb, in typescript is very unusual to use snake case.
In Tokilabs and in this project the use of snake case and kebab case is discouraged.
To enforce consistency in our codebase rename this, and all subsequent, variables in camelCase

2022-11-21 17:54 UTC, yfernandes requested changes

2022-11-21 17:54 UTC, yfernandes commented on libs/atqr/domain/src/lib/EmailService/templates/includes/base-style.scss
> +  $color_1: #272727;
As a rule of thumb, in typescript is very unusual to use snake case.
In Tokilabs and in this project the use of snake case and kebab case is discouraged.
To enforce consistency in our codebase rename this and all subsequent variables in camelCase.

I comend your effort in using variables in your Scss, 
however when naming variables be it in Scss, Html, Pug or Ts ALWAYS be semantic!
What does this variable represent? When is it used? I get none of these informations from this name.
Perhaps i can assume by the color that it is used as a text color, if so the variable should be named textColor or something along those lines

2022-11-21 17:54 UTC, yfernandes commented on libs/atqr/domain/src/lib/EmailService/templates/includes/base-style.scss
> +  $color_1: #272727;
Numbers in the variable name also aren't helpfull, try to avoid it at all costs.

2022-11-21 17:54 UTC, yfernandes commented on libs/atqr/domain/src/lib/EmailService/templates/includes/base-style.scss
> +  $border-color_1: rgba(0, 0, 0, 0.15);
Don't mix casing styles, either you use kebab case or snake case.
In this case neither is fine. Use camelCase

2022-11-23 16:03 UTC, yfernandes requested changes, later dismissed

2022-11-23 16:03 UTC, yfernandes commented on apps/atqr/web/src/pages/termsAndCondition/termsConditions.pug
> +    mixin terms(title, paragraph)
Infinite recursive call

2022-11-23 16:03 UTC, yfernandes commented on apps/atqr/web/src/pages/termsAndCondition/termsConditions.pug
> +    link(rel='stylesheet', href='./terms-style.css')
Before commiting check if all imports are working, this one isn't.

2022-11-23 16:03 UTC, yfernandes commented on apps/atqr/web/src/pages/termsAndCondition/termsConditions.pug
> +  script(src='../challenge/challenge.js')
Broken import

2022-11-23 16:03 UTC, yfernandes commented on apps/atqr/web/src/pages/termsAndCondition/termsConditions.pug
> +  //- JS
Avoid unnecessary comments

2022-11-23 16:03 UTC, yfernandes commented on apps/atqr/web/src/pages/termsAndCondition/termsConditions.pug
> +                Termos e condições gerais de uso (e de compra e venda) do OU site TODO:NOMEDOAPP
Replace placeholder by actual company name

2022-11-23 16:03 UTC, yfernandes commented on apps/atqr/web/src/pages/termsAndCondition/termsStyle.scss
> +      margin-left: 30px;
Use relative units.

2022-11-23 16:03 UTC, yfernandes commented on libs/atqr/domain/src/lib/EmailService/templates/includes/baseStyle.scss
> +  padding: 20px;
Use relative units

2022-11-23 16:03 UTC, yfernandes commented on libs/atqr/domain/src/lib/EmailService/templates/includes/baseTemplate.pug
>  mixin email-content(h1, p1, src, p2, p3, p4)
Refactor into more human readable parameter names

2022-11-23 16:03 UTC, yfernandes commented on libs/atqr/domain/src/lib/EmailService/templates/includes/baseTemplate.pug
>  mixin email-content(h1, p1, src, p2, p3, p4)
Rename function to camelCase

2022-11-23 16:03 UTC, yfernandes commented on apps/atqr/web/src/pages/termsAndCondition/termsConditions.pug
> +      h4.h4= title
@Saulo, im in a review meeting with the team and could use your input on the use of a class with the same name as the tag.

2022-11-24 17:14 UTC, yfernandes commented on apps/atqr/web/src/pages/termsAndCondition/termsConditions.pug
> +  script(src='../challenge/challenge.js')
Since the page was removed by force push this comment is resolved

2022-11-29 19:41 UTC, yfernandes reviewed
Your branch is not compiling, this being the case I can't see the end result. Please, make it compile again and ask for a new review.

2022-12-01 19:47 UTC, albnunes approved these changes
it`s ok

2022-12-01 19:48 UTC, merged