Raquel/atqr 127 create notifications value objects 2
tokilabs/atqr pull request #78
Opened 2023-01-12 17:30 UTC by raquellenn

Implemented the value objects especified in /concept-set/Notifications.disl

2023-01-16 20:33 UTC, rairezende requested changes
Is your ValueObject import really working? It should've been imported by scope.

2023-01-16 20:38 UTC, rairezende reviewed
Delete empty unneeded lines and use the prettier extension to make it easier to follow it's rules (they are requested in the linear review checklist).

2023-01-16 20:44 UTC, rairezende commented on libs/atqr/domain/src/lib/notifications/notification.valueObject.ts
> +enum NotificationCategory {
Enums implementation from Notifications.disl are not a part of your task. It's an issue assigned to another person.

2023-01-16 20:52 UTC, rairezende commented on libs/atqr/domain/src/lib/notifications/notification.valueObject.ts
> +    public readonly id = new Guid()
the "id" property should actually be the first one in the constructor, if you follow the pattern used until here.

2023-01-24 17:12 UTC, albnunes requested changes
it lacks a folder called valueObjects to organize it better.

remove the "valueObject" suffix from the filenames

make an index and export all the contents of that folder.

2023-01-24 17:14 UTC, albnunes requested changes
The isBeforeDay function is not necessary without another one that does the same

2023-01-26 18:19 UTC, svallory commented
Replaced by #83

2023-01-26 18:19 UTC, svallory commented
Replaced by #83

2023-01-26 18:19 UTC, closed without merging